### PR TITLE
making mobile freindly to hungryhub restaurant web page

### PR DESCRIPTION
**Pull request by Rajveer07**

### CODE REVIEW

**Comment by mehraTushar** [comment]
@Rajveer07 i dont use custom css in my project please use only tailwind classes as per my project standards and about responsiveness this is not how responsive websites look like 
i will explain this with proper requirement  

1. on smaller screen move left hand icons like home about contact and cart into hamburger menu you can use this icon from font awesome
 image

2. hide logo in small screen keep name as it is 
3. align resurant count with cards and navbar
4. same thing goes for search bar and filter buttons make search bar small in mobile screen and adjuts filter accordingly 
5. ui should contain same font size in whole page right now somewhere its small somewhere its big 
image

6. adjust footer allign this with cards for proper alignment 
image

**Comment by Rajveer07** [comment]
Okay got it , what should be the options in side the hamburger menu

**Comment by MehraTushar786** [comment]
> menu

Well all the right hand side navbar buttons will go under the hamburger menu like home about contact and cart button

**Comment by mehraTushar** [comment]
> Okay got it , what should be the options in side the hamburger menu

Well all the right hand side navbar buttons will go under the hamburger menu like home about contact and cart button

**Comment by Rajveer07** [comment]
okay

**Pull request closed without merging**
